os:
  - linux

language: php

php:
  - 7.2

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - sudo mysql -e 'create database anggota;'
  - composer self-update
  - composer install
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit