language: php

php:
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mysql -e 'create database anggota;'

before_script:
  - travis_retry composer self-update 1.8.6
  - composer update --prefer-lowest --no-interaction --prefer-source
  - composer install
  - cp .env.example .env
  - php artisan migrate:refresh --seed