os:
  - linux

language: php

php:
  - 7.2

services:
  - mysql

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  - composer self-update 1.8.6
  - composer --version
  - composer update
