os:
  - linux

language: php

php:
  - 7.2

services:
  - mysql

before_script:
  - php -r "copy('https://getcomposer.org/download/1.10.17/composer.phar', 'composer-setup.php');"
  - php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - composer -V

script:
  - vendor/bin/phpunit