os:
  - linux

language: php

php:
  - 7.2

services:
  - mysql

before_script:
  - composer self-update 1.8.6
  - composer --version
  - composer update
  - composer install

script:
  - vendor/bin/phpunit